services:
  postgres:
    image: postgres:18.4
    container_name: bluecollarhub-postgres
    environment:
      POSTGRES_DB: bluecollarhub_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped

volumes:
  postgres_data: